const tools = [
  { name: "Power BI", icon: "/logos/powerbi.svg", detail: "Dashboards, DAX y modelos semánticos" },
  { name: "Python", icon: "/logos/python.svg", detail: "pandas, openpyxl y automatización" },
  { name: "SAP Business One", icon: "/logos/sap.svg", detail: "OITM, catálogo y operaciones" },
  { name: "SQL", icon: "/logos/sql.svg", detail: "Consultas, cruces y modelado" },
  { name: "Tableau", icon: "/logos/tableau.svg", detail: "Visualización y reporting" },
  { name: "Excel", icon: "/logos/excel.svg", detail: "Power Query, Power Pivot y VBA" },
  { name: "Pandas", icon: "/logos/pandas.svg", detail: "Transformación y calidad de datos" },
  { name: "Selenium", icon: "/logos/selenium.svg", detail: "Validación web automatizada" },
  { name: "Qlik", icon: "/logos/qlik.svg", detail: "Análisis y aseguramiento de ingresos" },
  { name: "Looker Studio", icon: "/logos/looker.svg", detail: "Dashboards web interactivos" },
  { name: "GitHub", icon: "/logos/github.svg", detail: "Publicación de aplicaciones web" },
  { name: "Claude API", icon: "/logos/claude.svg", detail: "LLM integrados en procesos BI" },
];

const projects = [
  { id:"01", title:"Executive Sales Dashboard", category:"Power BI · Retail & eCommerce", summary:"Modelo ejecutivo para ventas, margen, inventario y comportamiento del cliente, con navegación desde KPI hasta producto.", impact:"Reporte semanal: 4 horas → 15 minutos", image:"/dashboard-ecommerce.png", url:null, tags:["Power BI","DAX","SAP B1","RFM","ABC Pareto"] },
  { id:"02", title:"Retail Performance Dashboard", category:"Power BI · Omnichannel", summary:"Vista comercial por canal, división, familia, campaña y tienda, integrando ventas, unidades, descuento, margen e inventario.", impact:"Fuente única para decisiones comerciales", image:"/dashboard-retail.png", url:null, tags:["Power BI","Power Query","Data Modeling","Retail"] },
  { id:"03", title:"Inventory Validation System", category:"Data Quality · PIM", summary:"Sistema de reglas y semáforos para validar atributos entre inventario SAP y una plataforma PIM antes de cada carga de catálogo.", impact:"85% menos errores de calidad", url:null, tags:["DAX","Power Query","SAP OITM","PIM"] },
  { id:"04", title:"SAP-to-PIM ETL Pipeline", category:"Python · Automatización", summary:"Pipeline de transformación de exportaciones SAP hacia archivos de productos padres e hijos, con validación de campos y códigos UPC.", impact:"Ciclo de 3 días → 4 horas", url:null, tags:["Python","pandas","openpyxl","ETL"] },
  { id:"05", title:"AI Product Content Pipeline", category:"Python · LLM", summary:"Flujo automatizado que transforma información estructurada en descripciones, características y especificaciones listas para PIM.", impact:"130+ SKUs procesados por ejecución", url:null, tags:["Claude API","Python","JSON","Excel"] },
  { id:"06", title:"Web Catalog Validator", category:"QA · eCommerce", summary:"Auditor automatizado de publicaciones para detectar discrepancias en imágenes, precio, descripción y disponibilidad.", impact:"300+ incidencias detectadas al mes", url:null, tags:["Selenium","pandas","openpyxl","QA"] },
  { id:"07", title:"Service Network Directory", category:"Looker Studio · Operaciones", summary:"Directorio interactivo para localizar proveedores por estado, municipio y capacidades operativas en una sola vista.", impact:"Consulta geográfica y de servicios centralizada", url:null, tags:["Looker Studio","Data Quality","Filtros"] },
  { id:"08", title:"Shipment Tracking Analytics Portal", category:"Web BI · Logística", summary:"Portal que concilia pedidos, almacén, transportistas y reembolsos, con búsqueda unificada y análisis desde KPI hasta orden.", impact:"Múltiples sistemas → un expediente operativo", url:"https://goku230491-cmd.github.io/CATALOGO-DE-RASTREO/", tags:["HTML","JavaScript","Data Reconciliation","Logística"] },
  { id:"09", title:"eCommerce Image & Catalog Finder", category:"Web App · PIM", summary:"Aplicación para auditar cobertura de imágenes, inventario y estados PIM/ERP mediante dashboard y catálogo visual filtrable.", impact:"Excepciones de catálogo visibles en segundos", url:"https://goku230491-cmd.github.io/IMAGENES-ECOMM/", tags:["HTML","JavaScript","PIM","eCommerce"] },
  { id:"10", title:"Competitive Intelligence Workspace", category:"Research · Data Storytelling", summary:"Workspace ejecutivo con indicadores de mercado, benchmark competitivo, cronología de noticias, FODA y fuentes públicas.", impact:"Noticias dispersas → narrativa ejecutiva", url:"https://goku230491-cmd.github.io/reebok-mx-dashboard/#noticias", tags:["Market Research","HTML","JavaScript","Storytelling"] },
];

const experience = [
  ["2025 — Actual","Data Analyst & AI-Driven BI","Reebok México","Power BI, SAP Business One, Python, automatización e integración de IA para retail y eCommerce."],
  ["2024 — 2025","Analista de Aseguramiento de Ingresos","Total Play","Qlik, conciliación entre sistemas, control de ingresos y reportes para finanzas."],
  ["2024","Analista de Integración de Datos","Casanova Rent","Integración, limpieza, homologación y dashboards operativos en BI y Looker Studio."],
  ["2021 — 2024","Analista de Logística","Estafeta Mexicana","KPI nacionales, análisis de mermas, incidencias y automatización de reportes."],
  ["2020 — 2021","Analista de Cuentas","Intercon","Dashboards de operación, personal, vacantes e incidencias a nivel nacional."],
  ["2018 — 2020","Coordinador de Inventarios","La Tendence","SAP Business One, inventarios, auditorías y control de 45 sucursales."],
  ["2015 — 2018","Consultor de Riesgo Contractual","Deloitte","Auditoría automotriz, inventarios físicos, procesos comerciales y control documental."],
];

const certifications = ["Maestría en Ciencia de Datos para Negocios · UTEL · En curso","Python de Cero a Experto · 50 horas · 2026","Qlik Sense: de cero a desarrollador · 2024","Tableau 2021 de la A a la Z · 2022","Microsoft Power BI Desktop · 2021","Visualización de Datos · Tec de Monterrey","SAP Business One · Administración y fundamentos","Ciencia de Datos Aplicada al Marketing · Anáhuac"];
const Arrow = () => <span aria-hidden="true">↗</span>;

export default function Home(){return <main>
  <nav className="nav-shell" aria-label="Navegación principal"><a className="brand" href="#inicio"><span>JC</span><strong>Jorge Castro</strong></a><div className="nav-links"><a href="#perfil">Perfil</a><a href="#proyectos">Proyectos</a><a href="#experiencia">Experiencia</a><a href="#contacto">Contacto</a></div><a className="nav-cta" href="/CV-Jorge-Castro.pdf" target="_blank">Descargar CV</a></nav>
  <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow"><span/> BI · DATA · AUTOMATION</p><h1>Datos que explican.<br/><em>Sistemas que resuelven.</em></h1><p className="hero-lead">Analista de Datos y Business Intelligence con más de 8 años transformando información compleja en decisiones, automatizaciones y productos analíticos que el negocio sí utiliza.</p><div className="hero-actions"><a className="button primary" href="#proyectos">Explorar proyectos <Arrow/></a><a className="button secondary" href="https://wa.me/527294930961" target="_blank">Hablemos por WhatsApp</a></div><div className="availability"><i/><span>Disponible para oportunidades en Toluca, Querétaro, México y remoto</span></div></div><div className="hero-visual"><div className="portrait-frame"><img src="/jorge-castro-clean.png" alt="Fotografía profesional de Jorge Luis Castro Páez"/></div></div></section>
  <section className="metric-strip" style={{gridTemplateColumns:"repeat(auto-fit, minmax(150px, 1fr))"}}><div><b>10</b><span>casos de portafolio</span></div><div><b>70–80%</b><span>menos tiempo manual</span></div><div><b>300+</b><span>errores detectados / mes</span></div><div><b>130+</b><span>SKUs automatizados</span></div><div><b>3 días → 4 h</b><span>en procesos de catálogo</span></div></section>
  <section className="section profile" id="perfil"><div className="section-heading"><p className="eyebrow"><span/> PERFIL</p><h2>Negocio, tecnología y ejecución.</h2></div><div className="profile-grid"><div className="profile-story"><p className="big-copy">Mi trabajo vive en la intersección entre <strong>Business Intelligence</strong>, automatización y entendimiento operativo.</p><p>Diseño modelos de datos confiables, dashboards ejecutivos y pipelines que conectan SAP, Excel, PIM, eCommerce y fuentes web. Mi experiencia en retail, logística, auditoría e inventarios me permite comprender el proceso completo, no solo la visualización final.</p><p>Actualmente desarrollo mi transición hacia analítica aplicada a infraestructura física de IA: centros de datos, energía, eficiencia operativa y operaciones industriales.</p></div><aside className="profile-card"><p className="mini-label">ENFOQUE ACTUAL</p><ul><li>Retail & eCommerce Analytics</li><li>Data Quality & PIM</li><li>Python Automation & ETL</li><li>Industrial & Infrastructure Analytics</li></ul><div className="language"><span>Idiomas</span><strong>Español nativo · Inglés intermedio</strong></div></aside></div></section>
  <section className="tool-section" id="herramientas"><div className="section-heading centered"><p className="eyebrow"><span/> STACK TÉCNICO <span/></p><h2>Herramientas que convierto en resultados.</h2></div><div className="tool-grid">{tools.map(t=><article className="tool-card" key={t.name}><div className="tool-icon"><img src={t.icon} alt={`Logotipo de ${t.name}`}/></div><h3>{t.name}</h3><p>{t.detail}</p></article>)}</div></section>
  <section className="section projects" id="proyectos"><div className="section-heading"><p className="eyebrow"><span/> PORTAFOLIO</p><h2>Proyectos que conectan datos con acción.</h2><p>Casos reales anonimizados. Las imágenes públicas utilizan datos sintéticos para proteger la confidencialidad.</p></div><div className="featured-grid">{projects.slice(0,2).map(p=><article className="featured-project" key={p.id}><div className="project-image"><img src={p.image} alt={`Vista anonimizada de ${p.title}`}/><span>Datos sintéticos</span></div><div className="project-body"><p className="project-category">{p.category}</p><h3>{p.title}</h3><p>{p.summary}</p><strong className="impact">{p.impact}</strong><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div><div className="project-grid">{projects.slice(2).map(p=><article className="project-card" key={p.id}><div className="project-top"><span>{p.id}</span><small>{p.category}</small></div><h3>{p.title}</h3><p>{p.summary}</p><strong className="impact">{p.impact}</strong>{p.url&&<a className="report-link" href={p.url} target="_blank" rel="noreferrer">Ver reporte en vivo <Arrow/></a>}<div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>
  <section className="dark-section" id="experiencia"><div className="section-heading"><p className="eyebrow light"><span/> TRAYECTORIA</p><h2>Más de ocho años entendiendo operaciones.</h2></div><div className="timeline">{experience.map(([date,role,company,desc],i)=><article className="timeline-row" key={role}><div className="timeline-date">{date}</div><div className="timeline-marker"><i/></div><div className="timeline-content"><span>{company}</span><h3>{role}</h3><p>{desc}</p></div>{i===0&&<b className="current">ACTUAL</b>}</article>)}</div></section>
  <section className="section education"><div className="section-heading"><p className="eyebrow"><span/> FORMACIÓN</p><h2>Aprendizaje aplicado al negocio.</h2></div><div className="education-grid"><article className="degree-card accent"><span>MAESTRÍA</span><h3>Ciencia de Datos para Negocios</h3><p>UTEL · En curso · Finalización prevista septiembre 2026</p></article><article className="degree-card"><span>LICENCIATURA</span><h3>Administración</h3><p>Universidad Autónoma del Estado de México · Titulado</p></article></div><div className="cert-grid">{certifications.map((c,i)=><div key={c}><span>{String(i+1).padStart(2,"0")}</span><p>{c}</p></div>)}</div></section>
  <section className="contact" id="contacto"><div><p className="eyebrow light"><span/> CONTACTO</p><h2>¿Tienes datos complejos?<br/><em>Convirtámoslos en decisiones.</em></h2><p>Disponible para roles de BI/Data Analyst, proyectos freelance y colaboraciones en automatización, retail, eCommerce e infraestructura.</p></div><div className="contact-links"><a href="mailto:jorgeluis.23-91@hotmail.com"><small>EMAIL</small><strong>jorgeluis.23-91@hotmail.com</strong><Arrow/></a><a href="https://wa.me/527294930961" target="_blank"><small>WHATSAPP</small><strong>+52 729 493 0961</strong><Arrow/></a><a href="https://www.linkedin.com/in/jorge-luis-castro-p%C3%A1ez-6727173a9/" target="_blank"><small>LINKEDIN</small><strong>Jorge Luis Castro Páez</strong><Arrow/></a><a href="/CV-Jorge-Castro.pdf" target="_blank"><small>CURRÍCULUM</small><strong>Descargar CV en PDF</strong><Arrow/></a></div></section>
  <footer><a className="brand" href="#inicio"><span>JC</span><strong>Jorge Castro</strong></a><p>Data Analyst · Business Intelligence · Automation</p><p>© 2026 · Toluca, Estado de México</p></footer>
</main>}
