"use client";

import { useEffect, useState } from "react";

type Language = "es" | "en";
type Localized = Record<Language, string>;

const tools = [
  { name:"Power BI", icon:"/logos/powerbi.svg", detail:{es:"Dashboards, DAX y modelos semánticos",en:"Dashboards, DAX and semantic models"} },
  { name:"Python", icon:"/logos/python.svg", detail:{es:"pandas, openpyxl y automatización",en:"pandas, openpyxl and automation"} },
  { name:"SAP Business One", icon:"/logos/sap.svg", detail:{es:"OITM, catálogo y operaciones",en:"OITM, catalogs and operations"} },
  { name:"SQL", icon:"/logos/sql.svg", detail:{es:"Consultas, cruces y modelado",en:"Queries, data joins and modeling"} },
  { name:"Tableau", icon:"/logos/tableau.svg", detail:{es:"Visualización y reporting",en:"Visualization and reporting"} },
  { name:"Excel", icon:"/logos/excel.svg", detail:{es:"Power Query, Power Pivot y VBA",en:"Power Query, Power Pivot and VBA"} },
  { name:"Pandas", icon:"/logos/pandas.svg", detail:{es:"Transformación y calidad de datos",en:"Data transformation and quality"} },
  { name:"Selenium", icon:"/logos/selenium.svg", detail:{es:"Validación web automatizada",en:"Automated web validation"} },
  { name:"Qlik", icon:"/logos/qlik.svg", detail:{es:"Análisis y aseguramiento de ingresos",en:"Analytics and revenue assurance"} },
  { name:"Looker Studio", icon:"/logos/looker.svg", detail:{es:"Dashboards web interactivos",en:"Interactive web dashboards"} },
  { name:"GitHub", icon:"/logos/github.svg", detail:{es:"Publicación de aplicaciones web",en:"Web application publishing"} },
  { name:"Claude API", icon:"/logos/claude.svg", detail:{es:"LLM integrados en procesos BI",en:"LLMs integrated into BI processes"} },
];

const projects = [
  { id:"01", title:"Executive Sales Dashboard", category:{es:"Power BI · Retail y eCommerce",en:"Power BI · Retail & eCommerce"}, summary:{es:"Modelo ejecutivo para ventas, margen, inventario y comportamiento del cliente, con navegación desde KPI hasta producto.",en:"Executive model for sales, margin, inventory and customer behavior, with navigation from KPI level down to individual products."}, impact:{es:"Reporte semanal: 4 horas → 15 minutos",en:"Weekly reporting: 4 hours → 15 minutes"}, image:"/dashboard-ecommerce.png", url:null, tags:["Power BI","DAX","SAP B1","RFM","ABC Pareto"] },
  { id:"02", title:"Retail Performance Dashboard", category:{es:"Power BI · Omnicanal",en:"Power BI · Omnichannel"}, summary:{es:"Vista comercial por canal, división, familia, campaña y tienda, integrando ventas, unidades, descuento, margen e inventario.",en:"Commercial view by channel, division, family, campaign and store, integrating sales, units, discounts, margin and inventory."}, impact:{es:"Fuente única para decisiones comerciales",en:"Single source for commercial decisions"}, image:"/dashboard-retail.png", url:null, tags:["Power BI","Power Query","Data Modeling","Retail"] },
  { id:"03", title:"Inventory Validation System", category:{es:"Calidad de datos · PIM",en:"Data Quality · PIM"}, summary:{es:"Sistema de reglas y semáforos para validar atributos entre inventario SAP y una plataforma PIM antes de cada carga de catálogo.",en:"Rule-based traffic-light system that validates attributes between SAP inventory and a PIM platform before each catalog upload."}, impact:{es:"85% menos errores de calidad",en:"85% fewer quality errors"}, url:null, tags:["DAX","Power Query","SAP OITM","PIM"] },
  { id:"04", title:"SAP-to-PIM ETL Pipeline", category:{es:"Python · Automatización",en:"Python · Automation"}, summary:{es:"Pipeline de transformación de exportaciones SAP hacia archivos de productos padres e hijos, con validación de campos y códigos UPC.",en:"Pipeline that transforms SAP exports into parent and child product files, with field and UPC code validation."}, impact:{es:"Ciclo de 3 días → 4 horas",en:"Cycle reduced from 3 days → 4 hours"}, url:null, tags:["Python","pandas","openpyxl","ETL"] },
  { id:"05", title:"AI Product Content Pipeline", category:{es:"Python · IA generativa",en:"Python · Generative AI"}, summary:{es:"Flujo automatizado que transforma información estructurada en descripciones, características y especificaciones listas para PIM.",en:"Automated workflow that turns structured information into PIM-ready descriptions, features and specifications."}, impact:{es:"130+ SKUs procesados por ejecución",en:"130+ SKUs processed per run"}, url:null, tags:["Claude API","Python","JSON","Excel"] },
  { id:"06", title:"Web Catalog Validator", category:{es:"QA · eCommerce",en:"QA · eCommerce"}, summary:{es:"Auditor automatizado de publicaciones para detectar discrepancias en imágenes, precio, descripción y disponibilidad.",en:"Automated publication auditor that detects discrepancies in images, price, descriptions and availability."}, impact:{es:"300+ incidencias detectadas al mes",en:"300+ issues detected per month"}, url:null, tags:["Selenium","pandas","openpyxl","QA"] },
  { id:"07", title:"Service Network Directory", category:{es:"Looker Studio · Operaciones",en:"Looker Studio · Operations"}, summary:{es:"Directorio interactivo para localizar proveedores por estado, municipio y capacidades operativas en una sola vista.",en:"Interactive directory for locating suppliers by state, municipality and operating capabilities in a single view."}, impact:{es:"Consulta geográfica y de servicios centralizada",en:"Centralized geographic and service lookup"}, url:null, tags:["Looker Studio","Data Quality","Filters"] },
  { id:"08", title:"Shipment Tracking Analytics Portal", category:{es:"Web BI · Logística",en:"Web BI · Logistics"}, summary:{es:"Portal que concilia pedidos, almacén, transportistas y reembolsos, con búsqueda unificada y análisis desde KPI hasta orden.",en:"Portal that reconciles orders, warehouses, carriers and refunds, with unified search and analysis from KPIs down to each order."}, impact:{es:"Múltiples sistemas → un expediente operativo",en:"Multiple systems → one operating record"}, url:"https://goku230491-cmd.github.io/CATALOGO-DE-RASTREO/", tags:["HTML","JavaScript","Data Reconciliation","Logistics"] },
  { id:"09", title:"eCommerce Image & Catalog Finder", category:{es:"Aplicación web · PIM",en:"Web App · PIM"}, summary:{es:"Aplicación para auditar cobertura de imágenes, inventario y estados PIM/ERP mediante dashboard y catálogo visual filtrable.",en:"Application for auditing image coverage, inventory and PIM/ERP status through a dashboard and filterable visual catalog."}, impact:{es:"Excepciones de catálogo visibles en segundos",en:"Catalog exceptions visible in seconds"}, url:"https://goku230491-cmd.github.io/IMAGENES-ECOMM/", tags:["HTML","JavaScript","PIM","eCommerce"] },
  { id:"10", title:"Competitive Intelligence Workspace", category:{es:"Investigación · Storytelling",en:"Research · Data Storytelling"}, summary:{es:"Workspace ejecutivo con indicadores de mercado, benchmark competitivo, cronología de noticias, FODA y fuentes públicas.",en:"Executive workspace with market indicators, competitive benchmarks, news timeline, SWOT analysis and public sources."}, impact:{es:"Noticias dispersas → narrativa ejecutiva",en:"Scattered news → executive narrative"}, url:"https://goku230491-cmd.github.io/reebok-mx-dashboard/#noticias", tags:["Market Research","HTML","JavaScript","Storytelling"] },
];

const experience = [
  {date:{es:"2025 — Actual",en:"2025 — Present"},role:{es:"Data Analyst & AI-Driven BI",en:"Data Analyst & AI-Driven BI"},company:"Reebok México",desc:{es:"Power BI, SAP Business One, Python, automatización e integración de IA para retail y eCommerce.",en:"Power BI, SAP Business One, Python, automation and AI integration for retail and eCommerce."}},
  {date:{es:"2024 — 2025",en:"2024 — 2025"},role:{es:"Analista de Aseguramiento de Ingresos",en:"Revenue Assurance Analyst"},company:"Total Play",desc:{es:"Qlik, conciliación entre sistemas, control de ingresos y reportes para finanzas.",en:"Qlik, cross-system reconciliation, revenue controls and finance reporting."}},
  {date:{es:"2024",en:"2024"},role:{es:"Analista de Integración de Datos",en:"Data Integration Analyst"},company:"Casanova Rent",desc:{es:"Integración, limpieza, homologación y dashboards operativos en BI y Looker Studio.",en:"Integration, cleansing, standardization and operational dashboards in BI and Looker Studio."}},
  {date:{es:"2021 — 2024",en:"2021 — 2024"},role:{es:"Analista de Logística",en:"Logistics Analyst"},company:"Estafeta Mexicana",desc:{es:"KPI nacionales, análisis de mermas, incidencias y automatización de reportes.",en:"National KPIs, loss and incident analysis, and report automation."}},
  {date:{es:"2020 — 2021",en:"2020 — 2021"},role:{es:"Analista de Cuentas",en:"Account Analyst"},company:"Intercon",desc:{es:"Dashboards de operación, personal, vacantes e incidencias a nivel nacional.",en:"National dashboards for operations, staffing, vacancies and incidents."}},
  {date:{es:"2018 — 2020",en:"2018 — 2020"},role:{es:"Coordinador de Inventarios",en:"Inventory Coordinator"},company:"La Tendence",desc:{es:"SAP Business One, inventarios, auditorías y control de 45 sucursales.",en:"SAP Business One, inventory, audits and control of 45 stores."}},
  {date:{es:"2015 — 2018",en:"2015 — 2018"},role:{es:"Consultor de Riesgo Contractual",en:"Contract Risk Consultant"},company:"Deloitte",desc:{es:"Auditoría automotriz, inventarios físicos, procesos comerciales y control documental.",en:"Automotive audits, physical inventory, commercial processes and document controls."}},
];

const certifications: Record<Language,string[]> = {
  es:["Maestría en Ciencia de Datos para Negocios · UTEL · En curso","Python de Cero a Experto · 50 horas · 2026","Qlik Sense: de cero a desarrollador · 2024","Tableau 2021 de la A a la Z · 2022","Microsoft Power BI Desktop · 2021","Visualización de Datos · Tec de Monterrey","SAP Business One · Administración y fundamentos","Ciencia de Datos Aplicada al Marketing · Anáhuac"],
  en:["Master's in Data Science for Business · UTEL · In progress","Python: Beginner to Expert · 50 hours · 2026","Qlik Sense: Beginner to Developer · 2024","Tableau 2021 from A to Z · 2022","Microsoft Power BI Desktop · 2021","Data Visualization · Tecnológico de Monterrey","SAP Business One · Administration and Fundamentals","Data Science Applied to Marketing · Anáhuac"],
};

const copy = {
  es:{navProfile:"Perfil",navProjects:"Proyectos",navExperience:"Experiencia",navContact:"Contacto",downloadCV:"Descargar CV",languageLabel:"Seleccionar idioma",heroLabel:"BI · DATOS · AUTOMATIZACIÓN",heroTitleA:"Datos que explican.",heroTitleB:"Sistemas que resuelven.",heroLead:"Analista de Datos y Business Intelligence con más de 8 años transformando información compleja en decisiones, automatizaciones y productos analíticos que el negocio sí utiliza.",explore:"Explorar proyectos",whatsapp:"Hablemos por WhatsApp",availability:"Disponible para oportunidades en Toluca, Querétaro, México y remoto",metrics:["casos de portafolio","menos tiempo manual","errores detectados / mes","SKUs automatizados","en procesos de catálogo"],profileLabel:"PERFIL",profileTitle:"Negocio, tecnología y ejecución.",profileBig:"Mi trabajo vive en la intersección entre Business Intelligence, automatización y entendimiento operativo.",profileP1:"Diseño modelos de datos confiables, dashboards ejecutivos y pipelines que conectan SAP, Excel, PIM, eCommerce y fuentes web. Mi experiencia en retail, logística, auditoría e inventarios me permite comprender el proceso completo, no solo la visualización final.",profileP2:"Actualmente desarrollo mi transición hacia analítica aplicada a infraestructura física de IA: centros de datos, energía, eficiencia operativa y operaciones industriales.",focus:"ENFOQUE ACTUAL",focusItems:["Retail y analítica eCommerce","Calidad de datos y PIM","Automatización y ETL con Python","Analítica industrial y de infraestructura"],languages:"Idiomas",languageValue:"Español nativo · Inglés intermedio",stackLabel:"STACK TÉCNICO",stackTitle:"Herramientas que convierto en resultados.",portfolioLabel:"PORTAFOLIO",portfolioTitle:"Proyectos que conectan datos con acción.",portfolioIntro:"Casos reales anonimizados. Las imágenes públicas utilizan datos sintéticos para proteger la confidencialidad.",synthetic:"Datos sintéticos",liveReport:"Ver reporte en vivo",careerLabel:"TRAYECTORIA",careerTitle:"Más de ocho años entendiendo operaciones.",current:"ACTUAL",educationLabel:"FORMACIÓN",educationTitle:"Aprendizaje aplicado al negocio.",master:"MAESTRÍA",masterTitle:"Ciencia de Datos para Negocios",masterDesc:"UTEL · En curso · Finalización prevista septiembre 2026",degree:"LICENCIATURA",degreeTitle:"Administración",degreeDesc:"Universidad Autónoma del Estado de México · Titulado",contactLabel:"CONTACTO",contactTitleA:"¿Tienes datos complejos?",contactTitleB:"Convirtámoslos en decisiones.",contactIntro:"Disponible para roles de BI/Data Analyst, proyectos freelance y colaboraciones en automatización, retail, eCommerce e infraestructura.",resume:"CURRÍCULUM",resumeAction:"Descargar CV en PDF",footer:"Analista de Datos · Business Intelligence · Automatización",location:"© 2026 · Toluca, Estado de México"},
  en:{navProfile:"Profile",navProjects:"Projects",navExperience:"Experience",navContact:"Contact",downloadCV:"Download CV",languageLabel:"Select language",heroLabel:"BI · DATA · AUTOMATION",heroTitleA:"Data that explains.",heroTitleB:"Systems that solve.",heroLead:"Data Analyst and Business Intelligence professional with 8+ years of experience turning complex information into decisions, automations and analytical products that businesses actually use.",explore:"Explore projects",whatsapp:"Chat on WhatsApp",availability:"Available for opportunities in Toluca, Querétaro, Mexico and remote roles",metrics:["portfolio cases","less manual work","issues detected / month","SKUs automated","in catalog processes"],profileLabel:"PROFILE",profileTitle:"Business, technology and execution.",profileBig:"My work sits at the intersection of Business Intelligence, automation and operational understanding.",profileP1:"I design reliable data models, executive dashboards and pipelines that connect SAP, Excel, PIM, eCommerce and web sources. My background in retail, logistics, auditing and inventory allows me to understand the entire process—not only the final visualization.",profileP2:"I am currently expanding into analytics applied to physical AI infrastructure: data centers, energy, operational efficiency and industrial operations.",focus:"CURRENT FOCUS",focusItems:["Retail & eCommerce Analytics","Data Quality & PIM","Python Automation & ETL","Industrial & Infrastructure Analytics"],languages:"Languages",languageValue:"Native Spanish · Intermediate English",stackLabel:"TECH STACK",stackTitle:"Tools I turn into results.",portfolioLabel:"PORTFOLIO",portfolioTitle:"Projects that connect data with action.",portfolioIntro:"Anonymized real-world cases. Public images use synthetic data to protect confidentiality.",synthetic:"Synthetic data",liveReport:"View live report",careerLabel:"CAREER",careerTitle:"Over eight years understanding operations.",current:"CURRENT",educationLabel:"EDUCATION",educationTitle:"Learning applied to business.",master:"MASTER'S",masterTitle:"Data Science for Business",masterDesc:"UTEL · In progress · Expected completion September 2026",degree:"BACHELOR'S",degreeTitle:"Business Administration",degreeDesc:"Autonomous University of the State of Mexico · Degree completed",contactLabel:"CONTACT",contactTitleA:"Do you have complex data?",contactTitleB:"Let's turn it into decisions.",contactIntro:"Available for BI/Data Analyst roles, freelance projects and collaborations in automation, retail, eCommerce and infrastructure.",resume:"RÉSUMÉ",resumeAction:"Download CV in PDF",footer:"Data Analyst · Business Intelligence · Automation",location:"© 2026 · Toluca, State of Mexico"},
};

const Arrow = () => <span aria-hidden="true">↗</span>;
const localize = (value:Localized, lang:Language) => value[lang];

export default function Home(){
  const [lang,setLang] = useState<Language>("es");
  const c = copy[lang];

  useEffect(()=>{
    const saved = window.localStorage.getItem("portfolio-language");
    if(saved === "es" || saved === "en") setLang(saved);
  },[]);

  useEffect(()=>{
    document.documentElement.lang = lang;
    window.localStorage.setItem("portfolio-language",lang);
  },[lang]);

  return <main>
    <nav className="nav-shell" aria-label={lang === "es" ? "Navegación principal" : "Main navigation"}>
      <a className="brand" href="#inicio"><span>JC</span><strong>Jorge Castro</strong></a>
      <div className="nav-links"><a href="#perfil">{c.navProfile}</a><a href="#proyectos">{c.navProjects}</a><a href="#experiencia">{c.navExperience}</a><a href="#contacto">{c.navContact}</a></div>
      <div className="nav-actions"><div className="language-switch" role="group" aria-label={c.languageLabel}><button type="button" className={lang==="es"?"active":""} aria-pressed={lang==="es"} onClick={()=>setLang("es")}>ES</button><button type="button" className={lang==="en"?"active":""} aria-pressed={lang==="en"} onClick={()=>setLang("en")}>EN</button></div><a className="nav-cta" href="/CV-Jorge-Castro.pdf" target="_blank" rel="noreferrer">{c.downloadCV}</a></div>
    </nav>

    <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow"><span/> {c.heroLabel}</p><h1>{c.heroTitleA}<br/><em>{c.heroTitleB}</em></h1><p className="hero-lead">{c.heroLead}</p><div className="hero-actions"><a className="button primary" href="#proyectos">{c.explore} <Arrow/></a><a className="button secondary" href="https://wa.me/527294930961" target="_blank" rel="noreferrer">{c.whatsapp}</a></div><div className="availability"><i/><span>{c.availability}</span></div></div><div className="hero-visual"><div className="portrait-frame"><img src="/jorge-castro-clean.png" alt={lang === "es" ? "Fotografía profesional de Jorge Luis Castro Páez" : "Professional portrait of Jorge Luis Castro Páez"}/></div></div></section>
    <section className="metric-strip" style={{gridTemplateColumns:"repeat(auto-fit, minmax(150px, 1fr))"}}><div><b>10</b><span>{c.metrics[0]}</span></div><div><b>70–80%</b><span>{c.metrics[1]}</span></div><div><b>300+</b><span>{c.metrics[2]}</span></div><div><b>130+</b><span>{c.metrics[3]}</span></div><div><b>{lang === "es" ? "3 días → 4 h" : "3 days → 4 h"}</b><span>{c.metrics[4]}</span></div></section>

    <section className="section profile" id="perfil"><div className="section-heading"><p className="eyebrow"><span/> {c.profileLabel}</p><h2>{c.profileTitle}</h2></div><div className="profile-grid"><div className="profile-story"><p className="big-copy">{c.profileBig}</p><p>{c.profileP1}</p><p>{c.profileP2}</p></div><aside className="profile-card"><p className="mini-label">{c.focus}</p><ul>{c.focusItems.map(item=><li key={item}>{item}</li>)}</ul><div className="language"><span>{c.languages}</span><strong>{c.languageValue}</strong></div></aside></div></section>

    <section className="tool-section" id="herramientas"><div className="section-heading centered"><p className="eyebrow"><span/> {c.stackLabel} <span/></p><h2>{c.stackTitle}</h2></div><div className="tool-grid">{tools.map(t=><article className="tool-card" key={t.name}><div className="tool-icon"><img src={t.icon} alt={`${lang === "es" ? "Logotipo de" : "Logo of"} ${t.name}`}/></div><h3>{t.name}</h3><p>{localize(t.detail,lang)}</p></article>)}</div></section>

    <section className="section projects" id="proyectos"><div className="section-heading"><p className="eyebrow"><span/> {c.portfolioLabel}</p><h2>{c.portfolioTitle}</h2><p>{c.portfolioIntro}</p></div><div className="featured-grid">{projects.slice(0,2).map(p=><article className="featured-project" key={p.id}><div className="project-image"><img src={p.image} alt={`${c.synthetic}: ${p.title}`}/><span>{c.synthetic}</span></div><div className="project-body"><p className="project-category">{localize(p.category,lang)}</p><h3>{p.title}</h3><p>{localize(p.summary,lang)}</p><strong className="impact">{localize(p.impact,lang)}</strong><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div><div className="project-grid">{projects.slice(2).map(p=><article className="project-card" key={p.id}><div className="project-top"><span>{p.id}</span><small>{localize(p.category,lang)}</small></div><h3>{p.title}</h3><p>{localize(p.summary,lang)}</p><strong className="impact">{localize(p.impact,lang)}</strong>{p.url&&<a className="report-link" href={p.url} target="_blank" rel="noreferrer">{c.liveReport} <Arrow/></a>}<div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>

    <section className="dark-section" id="experiencia"><div className="section-heading"><p className="eyebrow light"><span/> {c.careerLabel}</p><h2>{c.careerTitle}</h2></div><div className="timeline">{experience.map((item,i)=><article className="timeline-row" key={item.company}><div className="timeline-date">{localize(item.date,lang)}</div><div className="timeline-marker"><i/></div><div className="timeline-content"><span>{item.company}</span><h3>{localize(item.role,lang)}</h3><p>{localize(item.desc,lang)}</p></div>{i===0&&<b className="current">{c.current}</b>}</article>)}</div></section>

    <section className="section education"><div className="section-heading"><p className="eyebrow"><span/> {c.educationLabel}</p><h2>{c.educationTitle}</h2></div><div className="education-grid"><article className="degree-card accent"><span>{c.master}</span><h3>{c.masterTitle}</h3><p>{c.masterDesc}</p></article><article className="degree-card"><span>{c.degree}</span><h3>{c.degreeTitle}</h3><p>{c.degreeDesc}</p></article></div><div className="cert-grid">{certifications[lang].map((cert,i)=><div key={cert}><span>{String(i+1).padStart(2,"0")}</span><p>{cert}</p></div>)}</div></section>

    <section className="contact" id="contacto"><div><p className="eyebrow light"><span/> {c.contactLabel}</p><h2>{c.contactTitleA}<br/><em>{c.contactTitleB}</em></h2><p>{c.contactIntro}</p></div><div className="contact-links"><a href="mailto:jorgeluis.23-91@hotmail.com"><small>EMAIL</small><strong>jorgeluis.23-91@hotmail.com</strong><Arrow/></a><a href="https://wa.me/527294930961" target="_blank" rel="noreferrer"><small>WHATSAPP</small><strong>+52 729 493 0961</strong><Arrow/></a><a href="https://www.linkedin.com/in/jorge-luis-castro-p%C3%A1ez-6727173a9/" target="_blank" rel="noreferrer"><small>LINKEDIN</small><strong>Jorge Luis Castro Páez</strong><Arrow/></a><a href="/CV-Jorge-Castro.pdf" target="_blank" rel="noreferrer"><small>{c.resume}</small><strong>{c.resumeAction}</strong><Arrow/></a></div></section>
    <footer><a className="brand" href="#inicio"><span>JC</span><strong>Jorge Castro</strong></a><p>{c.footer}</p><p>{c.location}</p></footer>
  </main>;
}
